[phases.setup]
nixPkgs = ["nodejs_18", "nodePackages.npm"]

[phases.build]
cmds = [
  "npm run railway:build"
]

[phases.start]
cmd = "npm start"

[variables]
NODE_ENV = "production"
NPM_CONFIG_PRODUCTION = "false"
