[build]
builder = "nixpacks"
buildCommand = "npm run railway:build"

[deploy]
numReplicas = 1
sleepApplication = false
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
healthcheckPath = "/health"
healthcheckTimeout = 300

[environments.staging]
variables = { NODE_ENV = "staging", NPM_CONFIG_PRODUCTION = "false" }

[environments.production]  
variables = { NODE_ENV = "production", NPM_CONFIG_PRODUCTION = "false" }
